### ISSUE TITLE
use-delta-profiles not working, pull

### ISSUE THREAD

**Issue by willthrom** [pyroscope-io/godeltaprof#3]
Hi,

Try to make work the delta pprof without luck:

```
log-level: debug
scrape-configs:
  - job-name: testing-golang
    enabled-profiles: [cpu, mem, goroutines, mutex, block]
    use-delta-endpoints: true
    static-configs:    
      - application: golang-framework-local
        spy-name: gospy
        targets:
          - 'host.docker.internal:8000'
        labels:
          env: dev
```

We are using Gin Framework so we had to add the router:
        ```
pprof.Register(router)
	// Register Pyroscope delta profiler
	base := "/debug/pprof"
	prefixRouter := router.Group(base)
	{
		prefixRouter.GET("/delta_heap", gin.WrapF(deltapprof.Heap))
		prefixRouter.GET("/delta_block", gin.WrapF(deltapprof.Block))
		prefixRouter.GET("/delta_mutex", gin.WrapF(deltapprof.Mutex))
	}
```

which work as in the the browser, querying  "/debug/pprof/delta_heap"  a .gz file is download for the delta heap. (like heap.pprof.gz)

But the UI/server still only query the original pprof. Targets not configured for the delta.

Are we missing something in the config?
We dont see any mention to "delta" in the terminal debug logs when starting the pyros servers.
